name: OYP
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  dio:
  url_launcher: ^6.1.4
  url_launcher_android: ^6.0.17
  pin_code_fields: ^7.4.0
  bloc: ^8.0.2
  image_downloader: ^0.31.0
  liquid_pull_to_refresh: ^3.0.1
  intro_slider: ^3.0.3
  flutter_launcher_icons:
  flutter_signin_button: ^2.0.0
  flutter_paypal: 
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.13
  carousel_slider: ^4.1.1



flutter_icons:
  image_path: "oyp/Untitled-1.png" 
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - iyp/173815.png
    - iyp/IYP.png
    - iyp/iyp apps b.png
    - iyp/iyp programs b.png
    - iyp/iyp designs b.png
    - iyp/iyp apps.png
    - iyp/iyp programs.png
    - iyp/iyp designs.png
    - iyp/peakpx.jpg
    - iyp/signup.jpg
    - iyp/stars.png
    - iyp/worldMAp.jpg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
